# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
#  export PS1="[\[\e[36m\]\A\[\e[m\]]\[\e[36m\]\u\[\e[m\]@\[\e[35m\]\h\[\e[m\]:\[\e[31m\]\w\[\e[m\]\\$ "
# PS1="\e[5;107;30m\A"
#PS1="\e[5;107;30m\t \e[5;101;97m   \u@\h \e[5;106;91m  \e[5;106;30m \w \e[5;49;96m    \\$    \e[0m";
#PS1="\e[5;107;30m\t \e[5;104;97m   \u@\h \e[5;106;94m  \e[5;106;30m \w \e[5;49;96m    \\$    \e[0m";

#export PS1="\[\e[5;47;30m\]\t \[\e[0m\] \[\e[1;46;37m\]  \[\e[0m\] \[\e[0;46;97m\] \u@\h \[\e[0m\] \[\e[0;45;36m\]   \[\e[0m\] \[\e[1;45;37m\] \w  \[\e[0m\] \[\e[0;49;35m\]    \\$    \[\e[0m\]";


#PS1="$(echo "${PS1}" | tr -d '[:space:]')"

#export  PROMPT_COMMAND='echo -ne "\033]0;${USERNAME}@${HOSTNAME}:${PWD/#$HOME/~}\007"'

PROMPT_COMMAND=__prompt_command # Func to gen PS1 after CMDs

__prompt_command() {
    local EXIT="$?"             # This needs to be first
    PS1=""

    local RCol='\[\e[0m\]'

    local Red='\[\e[0;31m\]'
    local Gre='\[\e[0;32m\]'
    local BYel='\[\e[1;33m\]'
    local BBlu='\[\e[1;34m\]'
    local Pur='\[\e[0;35m\]'

    if [ $EXIT != 0 ]; then
        PS1+="${Red}\u${RCol}"      # Add red if exit code non 0
    else
        PS1+="${Gre}\u${RCol}"
    fi

    PS1+="${RCol}@${BBlu}\h ${Pur}\W${BYel}\\$ ${RCol}"    
    echo -ne "\e]0;${USERNAME}@${HOSTNAME}:${PWD}\a"
}


alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ll='ls -ltra --color=auto'

#cd ~



s() {
  	ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 $1 $2 $3 $4 -t 'echo "
# .bashrc

# User specific aliases and functions

alias rm='"'"'rm -i'"'"'
alias cp='"'"'cp -i'"'"'
alias mv='"'"'mv -i'"'"'
alias grep='"'"'grep --color=auto'"'"'
alias ls='"'"'ls --color=auto'"'"'
alias egrep='"'"'egrep --color=auto'"'"'
alias fgrep='"'"'fgrep --color=auto'"'"'


# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi


PROMPT_COMMAND=__prompt_command # Func to gen PS1 after CMDs

__prompt_command() {
    local EXIT=\"\$?\"             # This needs to be first
    PS1=\"\"

    local RCol='"'"'\\[\\e[0m\\]'"'"'

    local Red='"'"'\\[\\e[0;31m\\]'"'"'
    local Gre='"'"'\\[\\e[0;32m\\]'"'"'
    local BYel='"'"'\\[\\e[1;33m\\]'"'"'
    local BBlu='"'"'\\[\\e[1;34m\\]'"'"'
    local Pur='"'"'\\[\\e[0;35m\\]'"'"'

    if [ \$EXIT != 0 ]; then
        PS1+=\"\${Red}\\u\${RCol}\"      # Add red if exit code non 0
    else
        PS1+=\"\${Gre}\\u\${RCol}\"
    fi

    PS1+=\"\${RCol}@\${BYel}\\h \${Pur}\\W\${BYel}\\\\$ \${RCol}\"    
    echo -ne \"\\e]0;\${USERNAME:-\$USER}@\${HOSTNAME}:\${PWD}\\a\"
}

        test ! -d ~/.ssh && mkdir ~/.ssh;
        test ! -f ~/.ssh/authorized_keys && touch ~/.ssh/authorized_keys;
        cats=\$(cat ~/.ssh/authorized_keys | grep -c -i igors);
        if [ \$cats -lt 1 ]; then
          echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCxCYwcN6gBSiCdJiFc5Xl2bsc4p7CxBT33CgVdE8Zy6bqkoZKEAkwJ1Wss3c1oeNvkGEKtDj5taVLS07YJEE8i12tLZXgjtbso3y1qVd/hodZHy1PZaWUwm6cvVfwhA8D93cnsa+JV6y8XzZrEV77LWjB25EUMHOvnvEzF+WiI6KHAm/u53GhLPfy6eDeuniIVu44Je39QDFTzwaw7dPgX7/Xwb4OpU8iF3BOCNxDVIc77KY9rNopgOP4erBe5E6HuAK3I83RV5O4bZVDACyMZyAZ5TFZ6RR1E7veCwFPaXKrRA3moQK4uV+6wD/sMUGSsAdvpTQ4S9tEIYvQmMPihV4aT0YESHBgUhD61nFoNeOqf95bQq3xw23lNGcHfhykBothraXd51P2idJIuZIG5HJnySZGi1O/ZXxUaqYAq+T9d73MNYeHhXm5NMGP6i4y0ZVCk0zmdx2Y7T4io/ChpD/BLrjCdXyUHp43VqKGr9xWxMlvWV4k6xf6NLSx6uGE= igors@RKTI-PC1G >> ~/.ssh/authorized_keys;
        fi
" > ~/.bashrc.2019;
exec /bin/bash --rcfile ~/.bashrc.2019;'
}


